export const yjsConsts = {
  MESSAGE_SYNC: 0,
  MESSAGE_AWARENESS: 1,
  MESSAGE_AUTH: 2,
  MESSAGE_QUERY_AWARENESS: 3,

  MESSAGE_DELETE_ACCOUNT: 10,
  MESSAGE_CHANGE_USER_ID: 11,
  MESSAGE_CHANGE_PASSWORD: 12,
  MESSAGE_CHANGE_ADMIN_PASSWORD: 13,

  MESSAGE_TEST: 20,
  MESSAGE_TEST_CLOSE: 21,
};
